Release 202211.0
spryker-shop/b2c-demo-shop pull request #159
Opened 2022-11-23 10:04 UTC by DmitryLymarenko

#### Overview

Release 202211.0

2022-11-24 13:35 UTC, dmiseev approved these changes

2022-11-24 15:41 UTC, FRITS-Kh approved these changes

2022-11-24 16:19 UTC, limeeugenia approved these changes

2022-11-24 19:36 UTC, FRITS-Kh requested changes

2022-11-24 19:36 UTC, FRITS-Kh commented on .github/workflows/ci.yml
>          env:
Please update the `node-version` version from `12` to `16` and the `Frontend install-dependencies` according to the [suite](https://github.com/spryker-shop/suite/blob/master/.github/workflows/ci.yml#L117)

2022-11-25 09:10 UTC, FRITS-Kh requested changes

2022-11-25 09:10 UTC, FRITS-Kh commented on package.json
>          "@spryker/frontend-config.eslint": "~0.0.2",
devDependencies `"prettier": "~2.5.1"` and `"@prettier/plugin-xml": "~0.13.1"` are missed.

2022-11-25 10:00 UTC, FRITS-Kh approved these changes

2022-11-25 14:04 UTC, limeeugenia approved these changes

2022-11-25 17:32 UTC, merged