FRW-1198 Dynamic Store integration.
spryker-shop/b2c-demo-shop pull request #230
Opened 2023-05-12 11:14 UTC by geega

#### Overview

- Ticket: https://spryker.atlassian.net/browse/FRW-1198

2023-05-15 15:47 UTC, asmarovydlo requested changes
PR contains 11 files less than b2b integration. (Some of them are b2b related stuff, but some are not), please doublecheck check all of them, some that missed for sure:
- config/install/docker.ci.api.yml
- src/Pyz/Zed/AvailabilityNotification/Presentation/Mail/subscribed.text.twig
- ProductManagementLocalizedAttributesExtractorStep.php
- ProductSearchAttributeWriter.php
- ProductSetWriterStep.php
- CalculationWithCalculableObjectFacadeTest.php
- tests/PyzTest/Zed/Calculation/_support/CalculationBusinessTester.php

2023-05-17 09:05 UTC, geega commented
- config/install/docker.ci.api.yml - this file not changed in suite-nonsplit. Mb remove it in b2b PR
- src/Pyz/Zed/AvailabilityNotification/Presentation/Mail/subscribed.text.twig - Fixed 
- ProductManagementLocalizedAttributesExtractorStep.php  - Fixed
- ProductSetWriterStep.php - Fixed
- CalculationWithCalculableObjectFacadeTest. Don't have `createFixtureDataForTestCases` method for update
- tests/PyzTest/Zed/Calculation/_support/CalculationBusinessTester.php - this Tester is empty

2023-05-17 12:25 UTC, asmarovydlo approved these changes

2023-05-23 16:36 UTC, asmarovydlo requested changes
Exactly the same issues as for b2b PR https://github.com/spryker-shop/b2b-demo-shop/pull/173

2023-05-24 10:33 UTC, asmarovydlo approved these changes

2023-05-24 13:28 UTC, merged